### ISSUE TITLE
Multiple ScaledObject with one scaleTargetRef are not supported

### ISSUE THREAD

**Issue by voron** [dysnix/pancakeswap-ifo-scaler#1]
It seems that multiple `ScaledObject` referencing single `scaleTargetRef` are not supported with current Keda implementation.
Keda creates independent HPA objects for each `ScaledObject`, which leads to HPA wars to scale single resource.

```
k get hpa
NAME                                                          REFERENCE          TARGETS                                    MINPODS   MAXPODS   REPLICAS   AGE
keda-hpa-bsc-so                                               CloneSet/bsc-rpc   891/1200 (avg), 500m/1 (avg) + 1 more...   2         30        2          244d
keda-hpa-ifo-0x80828b68d126741eea62b4712ebf7ceb9d54cbaa-mgp   CloneSet/bsc-rpc   -9223372036854775808m/1 (avg)              1         100       2          3m38s
```
Proposed fix is to patch existing `ScaledObject` instead of creating a new one.

**Comment by daniel-yavorovich** [comment]
Fixed by change architecture to full regenerate scaledobject on update IFO or any settings.
